@US22
  Feature: US22_Admin ekleme

    Scenario:Admin, admin ekleyebilir....
    Given Admin "page_url" gider....
      When Teacherin page'de oldugu dogrulanir.
    When Admin logini tiklar....
    When Admin kullanici adini "Admin_user_name" girer....
    When Admin kullanici parolasini "Admin_password" girer....
    When Admin maviLogin'i tiklar....
      When Adminin giris yaptigi dogrulanir.
    When Admin Name kutusuna "Sadik" yazar....
    When Admin Surname kutusuna "Kalfa" yazar....
    When Admin Birth Place kutusuna "Turkey" yazar....
    When Admin Gender secmeli, "Male" tiklar....
    When Admin Date Of Birth girmeli "1.01.1984" yazar.....
    When Admin Phone bilgileri girmeli "555-888-8524" girer....
    When Admin gecerli bir ssn bilgisi girmeli "444-52-7458" girer....
    When Admin bir user name girer "SadikKalfaAdmin" girer....
    When Admin bir password girer "12345678"....
    When Admin submit butonuna basar....

